onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /top/dut/PCLK
add wave -noupdate /top/dut/PRESETn
add wave -noupdate /top/dut/PADDR
add wave -noupdate /top/dut/PWDATA
add wave -noupdate /top/dut/PRDATA
add wave -noupdate /top/dut/PWRITE
add wave -noupdate /top/dut/PENABLE
add wave -noupdate /top/dut/PSEL
add wave -noupdate /top/dut/PREADY
add wave -noupdate /top/dut/PSLVERR
add wave -noupdate /top/dut/IRQ
add wave -noupdate /top/dut/TXD
add wave -noupdate /top/dut/RXD
add wave -noupdate /top/dut/nRTS
add wave -noupdate /top/dut/nDTR
add wave -noupdate /top/dut/nOUT1
add wave -noupdate /top/dut/nOUT2
add wave -noupdate /top/dut/nCTS
add wave -noupdate /top/dut/nDSR
add wave -noupdate /top/dut/nDCD
add wave -noupdate /top/dut/nRI
add wave -noupdate /top/dut/baud_o
add wave -noupdate -group REGISTERS /top/dut/control/LCR
add wave -noupdate -group REGISTERS /top/dut/control/IER
add wave -noupdate -group REGISTERS /top/dut/control/IIR
add wave -noupdate -group REGISTERS /top/dut/control/FCR
add wave -noupdate -group REGISTERS /top/dut/control/MCR
add wave -noupdate -group REGISTERS /top/dut/control/MSR
add wave -noupdate -group REGISTERS /top/dut/control/LSR
add wave -noupdate /top/dut/tx_fifo_we
add wave -noupdate /top/dut/tx_enable
add wave -noupdate /top/dut/tx_fifo_count
add wave -noupdate /top/dut/tx_fifo_empty
add wave -noupdate /top/dut/tx_fifo_full
add wave -noupdate /top/dut/tx_busy
add wave -noupdate /top/dut/rx_data_out
add wave -noupdate /top/dut/rx_idle
add wave -noupdate /top/dut/rx_overrun
add wave -noupdate /top/dut/parity_error
add wave -noupdate /top/dut/framing_error
add wave -noupdate /top/dut/break_error
add wave -noupdate /top/dut/rx_fifo_count
add wave -noupdate /top/dut/rx_fifo_empty
add wave -noupdate /top/dut/push_rx_fifo
add wave -noupdate /top/dut/rx_enable
add wave -noupdate /top/dut/rx_fifo_re
add wave -noupdate /top/dut/loopback
add wave -noupdate /top/dut/LCR
add wave -noupdate /top/dut/rx_fifo_full
add wave -noupdate /top/dut/TXDout
add wave -noupdate /top/dut/RXDin
add wave -noupdate /top/dut/control/PCLK
add wave -noupdate /top/dut/control/PRESETn
add wave -noupdate /top/dut/control/PSEL
add wave -noupdate /top/dut/control/PWRITE
add wave -noupdate /top/dut/control/PENABLE
add wave -noupdate /top/dut/control/PADDR
add wave -noupdate /top/dut/control/PWDATA
add wave -noupdate /top/dut/control/PRDATA
add wave -noupdate /top/dut/control/PREADY
add wave -noupdate /top/dut/control/PSLVERR
add wave -noupdate /top/dut/control/tx_fifo_we
add wave -noupdate /top/dut/control/tx_enable
add wave -noupdate /top/dut/control/tx_fifo_count
add wave -noupdate /top/dut/control/tx_fifo_empty
add wave -noupdate /top/dut/control/tx_fifo_full
add wave -noupdate /top/dut/control/tx_busy
add wave -noupdate /top/dut/control/rx_data_out
add wave -noupdate /top/dut/control/rx_idle
add wave -noupdate /top/dut/control/rx_overrun
add wave -noupdate /top/dut/control/parity_error
add wave -noupdate /top/dut/control/framing_error
add wave -noupdate /top/dut/control/break_error
add wave -noupdate /top/dut/control/rx_fifo_count
add wave -noupdate /top/dut/control/rx_fifo_empty
add wave -noupdate /top/dut/control/rx_fifo_full
add wave -noupdate /top/dut/control/push_rx_fifo
add wave -noupdate /top/dut/control/rx_enable
add wave -noupdate /top/dut/control/rx_fifo_re
add wave -noupdate /top/dut/control/loopback
add wave -noupdate /top/dut/control/ctsn
add wave -noupdate /top/dut/control/dsrn
add wave -noupdate /top/dut/control/dcdn
add wave -noupdate /top/dut/control/rin
add wave -noupdate /top/dut/control/rtsn
add wave -noupdate /top/dut/control/dtrn
add wave -noupdate /top/dut/control/out1n
add wave -noupdate /top/dut/control/out2n
add wave -noupdate /top/dut/control/irq
add wave -noupdate /top/dut/control/baud_o
add wave -noupdate /top/dut/control/tx_state
add wave -noupdate /top/dut/control/rx_state
add wave -noupdate /top/dut/control/we
add wave -noupdate /top/dut/control/re
add wave -noupdate /top/dut/control/rx_fifo_over_threshold
add wave -noupdate /top/dut/control/DIVISOR
add wave -noupdate /top/dut/control/dlc
add wave -noupdate /top/dut/control/enable
add wave -noupdate /top/dut/control/start_dlc
add wave -noupdate /top/dut/control/rx_enabled
add wave -noupdate /top/dut/control/tx_enabled
add wave -noupdate /top/dut/control/rx_overrun_int
add wave -noupdate /top/dut/control/reset_overrun
add wave -noupdate /top/dut/control/tx_int
add wave -noupdate /top/dut/control/rx_int
add wave -noupdate /top/dut/control/rx_parity_int
add wave -noupdate /top/dut/control/rx_framing_int
add wave -noupdate /top/dut/control/rx_break_int
add wave -noupdate /top/dut/control/cts_0
add wave -noupdate /top/dut/control/cts_1
add wave -noupdate /top/dut/control/cts_int
add wave -noupdate /top/dut/control/dcd_0
add wave -noupdate /top/dut/control/dcd_1
add wave -noupdate /top/dut/control/dcd_int
add wave -noupdate /top/dut/control/dsr_0
add wave -noupdate /top/dut/control/dsr_1
add wave -noupdate /top/dut/control/dsr_int
add wave -noupdate /top/dut/control/ri_0
add wave -noupdate /top/dut/control/ri_1
add wave -noupdate /top/dut/control/ri_int
add wave -noupdate /top/dut/control/ms_int
add wave -noupdate /top/dut/control/nDCD_1
add wave -noupdate /top/dut/control/nCTS_1
add wave -noupdate /top/dut/control/nDSR_1
add wave -noupdate /top/dut/control/nRI_1
add wave -noupdate /top/dut/control/ls_int
add wave -noupdate /top/dut/control/fifo_error
add wave -noupdate /top/dut/control/last_tx_fifo_empty
add wave -noupdate /top/dut/control/fsm_state
add wave -noupdate /top/dut/tx_channel/PCLK
add wave -noupdate /top/dut/tx_channel/PRESETn
add wave -noupdate /top/dut/tx_channel/PWDATA
add wave -noupdate /top/dut/tx_channel/tx_fifo_push
add wave -noupdate /top/dut/tx_channel/LCR
add wave -noupdate /top/dut/tx_channel/enable
add wave -noupdate /top/dut/tx_channel/tx_fifo_empty
add wave -noupdate /top/dut/tx_channel/tx_fifo_full
add wave -noupdate /top/dut/tx_channel/tx_fifo_count
add wave -noupdate /top/dut/tx_channel/busy
add wave -noupdate /top/dut/tx_channel/TXD
add wave -noupdate /top/dut/tx_channel/tx_state
add wave -noupdate /top/dut/tx_channel/bit_counter
add wave -noupdate /top/dut/tx_channel/tx_buffer
add wave -noupdate /top/dut/tx_channel/tx_fifo_out
add wave -noupdate /top/dut/tx_channel/pop_tx_fifo
add wave -noupdate /top/dut/tx_channel/tx_fifo/clk
add wave -noupdate /top/dut/tx_channel/tx_fifo/rstn
add wave -noupdate /top/dut/tx_channel/tx_fifo/push
add wave -noupdate /top/dut/tx_channel/tx_fifo/pop
add wave -noupdate /top/dut/tx_channel/tx_fifo/data_in
add wave -noupdate /top/dut/tx_channel/tx_fifo/fifo_empty
add wave -noupdate /top/dut/tx_channel/tx_fifo/fifo_full
add wave -noupdate /top/dut/tx_channel/tx_fifo/count
add wave -noupdate /top/dut/tx_channel/tx_fifo/data_out
add wave -noupdate /top/dut/tx_channel/tx_fifo/ip_count
add wave -noupdate /top/dut/tx_channel/tx_fifo/op_count
add wave -noupdate /top/dut/rx_channel/PCLK
add wave -noupdate /top/dut/rx_channel/PRESETn
add wave -noupdate /top/dut/rx_channel/RXD
add wave -noupdate /top/dut/rx_channel/pop_rx_fifo
add wave -noupdate /top/dut/rx_channel/enable
add wave -noupdate /top/dut/rx_channel/LCR
add wave -noupdate /top/dut/rx_channel/rx_idle
add wave -noupdate /top/dut/rx_channel/rx_fifo_out
add wave -noupdate /top/dut/rx_channel/rx_fifo_count
add wave -noupdate /top/dut/rx_channel/push_rx_fifo
add wave -noupdate /top/dut/rx_channel/rx_fifo_empty
add wave -noupdate /top/dut/rx_channel/rx_fifo_full
add wave -noupdate /top/dut/rx_channel/rx_overrun
add wave -noupdate /top/dut/rx_channel/parity_error
add wave -noupdate /top/dut/rx_channel/framing_error
add wave -noupdate /top/dut/rx_channel/break_error
add wave -noupdate /top/dut/rx_channel/rx_state
add wave -noupdate /top/dut/rx_channel/bit_counter
add wave -noupdate /top/dut/rx_channel/rx_buffer
add wave -noupdate /top/dut/rx_channel/filter
add wave -noupdate /top/dut/rx_channel/filtered_rxd
add wave -noupdate /top/dut/rx_channel/rx_fifo/clk
add wave -noupdate /top/dut/rx_channel/rx_fifo/rstn
add wave -noupdate /top/dut/rx_channel/rx_fifo/push
add wave -noupdate /top/dut/rx_channel/rx_fifo/pop
add wave -noupdate /top/dut/rx_channel/rx_fifo/data_in
add wave -noupdate /top/dut/rx_channel/rx_fifo/fifo_empty
add wave -noupdate /top/dut/rx_channel/rx_fifo/fifo_full
add wave -noupdate /top/dut/rx_channel/rx_fifo/count
add wave -noupdate /top/dut/rx_channel/rx_fifo/data_out
add wave -noupdate /top/dut/rx_channel/rx_fifo/ip_count
add wave -noupdate /top/dut/rx_channel/rx_fifo/op_count
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {7 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 230
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {146 ns}
